# Generated by Django 4.2.7 on 2023-11-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("studyapp", "0003_remove_assignment_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="assignment",
            name="course",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AddField(
            model_name="assignment",
            name="description",
            field=models.CharField(default="SOME STRING", max_length=255),
        ),
        migrations.AddField(
            model_name="assignment",
            name="dueDate",
            field=models.DateTimeField(default="no date"),
        ),
        migrations.AddField(
            model_name="assignment",
            name="title",
            field=models.CharField(default="SOME STRING", max_length=50),
        ),
        migrations.AddField(
            model_name="assignment",
            name="user",
            field=models.ForeignKey(
                default="test",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
