# Generated by Django 4.2.7 on 2023-11-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("studyapp", "0004_assignment_completed_assignment_course_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignment",
            name="dueDate",
            field=models.DateTimeField(),
        ),
    ]
