# Generated by Django 4.2.7 on 2023-11-05 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("studyapp", "0005_alter_assignment_duedate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="dueDate",
        ),
    ]
